### ISSUE TITLE
Promises don't randomly cancel

### ISSUE THREAD

**Issue by thomascgray** [sovietspaceship/javascript-on-northern-rail#1]
As a user of northern rail, I'm well aware that trains randomly cancel all the time.

At time of writing, the `Promise`s created by this library never randomly cancel.

Please fix.

**Comment by sovietspaceship2** [comment]
Thanks for reporting the issue. I fixed this in commit 7483e6b, make sure you update to the new, improved version

**Comment by thomascgray** [comment]
Thank you for the great work.

The library now randomly delays promises, and also randomly cancels some too, it's incredibly annoying.

That makes this library perfect. 11/10 highly recommend, would install again.
